{
  "uid" : "57ef10a9027e155c",
  "name" : "tmp_sber.test_main.MainTest.test_currencies_change_5_CZK",
  "fullName" : "tmp_sber.test_main.tmp_sber.test_main.MainTest.test_currencies_change_5_CZK",
  "historyId" : "14f2a13277176f9fa7c48456becb6f40",
  "time" : {
    "start" : 1533291164558,
    "stop" : 1533291171642,
    "duration" : 7084
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "failed",
  "statusMessage" : "AssertionError: Conversion result did not provided.\nCase: from 0 CZK to EUR",
  "statusTrace" : "Traceback (most recent call last):\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 331, in run\n    testMethod()\n  File \"/Library/Python/2.7/site-packages/parameterized/parameterized.py\", line 392, in standalone_func\n    return func(*(a + p.args), **p.kwargs)\n  File \"/Users/k.kvasnikov/PycharmProjects/tmp_sber/test_main.py\", line 95, in test_currencies_change\n    to_=cur_to))\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 412, in fail\n    raise self.failureException(msg)\nAssertionError: Conversion result did not provided.\nCase: from 0 CZK to EUR",
  "flaky" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "tmp_sber.test_main"
  }, {
    "name" : "testClass",
    "value" : "tmp_sber.test_main"
  }, {
    "name" : "testMethod",
    "value" : "tmp_sber.test_main.MainTest.test_currencies_change_5_CZK"
  }, {
    "name" : "package",
    "value" : "tmp_sber.test_main"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "57ef10a9027e155c.json",
  "parameterValues" : [ ]
}